function tableout = importProfili(workbookFile,sheetName)
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   table.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   Profili = importfile('Profili.xls','HD',2,38);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/04/27 16:13:47

[~, ~, raw] = xlsread(workbookFile, sheetName); % acquisisce tutto il contenuto del foglio excel
tableout = cell2table(raw(2:end,:));  % converte la cella in tabella
varnames = raw(1,:);
varunits = cell(size(varnames));
for i = 1:length(varnames)
    varname_ =  regexp(raw{1,i}, ' ', 'split');
    varname_{1} = regexprep(varname_{1}, ',', '_');
    varnames{1,i} = varname_{1};
    
    if length(varname_) > 1
        varunit_ = varname_(2);
    else
        varunit_ = {''};
    end
    varunits(1,i) = varunit_;
    clear('varname_', 'varunit_');
end
tableout.Properties.VariableNames = varnames;
tableout.Properties.VariableUnits = varunits;

tableout = sortrows(tableout,'g','ascend');


end